/* Autogenerated by build.rs. Do not edit. */

pub const IDI_APP_ICON: usize = 1001;
pub const IDS_APP_TITLE: usize = 1001;
pub const IDS_EXIT: usize = 1002;
pub const IDS_KEEPING_AUDIO_DEVICE_AWAKE: usize = 1003;
pub const IDS_APP_IS_ALREADY_RUNNING: usize = 1004;
